version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: talenttrek-server-container
    volumes:
      - ./server/data_output:/app/data_output
      - ./server/config/urls.json:/app/src/config/urls.json
    working_dir: /app
    entrypoint: ["uvicorn", "src.api.v1:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: talenttrek-app-container
    ports:
      - "3000:80"
    depends_on:
      - server
