version: "3.8"

services:
  server:
    build:
      context: ../../server
      dockerfile: Dockerfile.dev
    container_name: talenttrek-server-dev
    volumes:
      - ../../server:/app
      - ../../server/data_output:/app/data_output
      - ../../server/config:/app/src/config
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - ../../server/.env
    environment:
      - PYTHONPATH=/app
    command: ["uvicorn", "src.api.v1:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  app:
    build:
      context: ../../app
      dockerfile: Dockerfile.dev
    container_name: talenttrek-app-dev
    volumes:
      - ../../app:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development
      - VITE_HMR_HOST=0.0.0.0
    command: ["npm", "run", "dev"] 