sources:
  # =============================================================================
  # API-BASED SOURCES (No authentication, structured data)
  # =============================================================================
  
  - id: linkedin_api
    name: LinkedIn
    type: api
    api_url: "https://api.linkedin.com/v2/jobs?keywords={keyword}&count=50"
    data_mapping:
      title: "title"
      company: "company.name"
      location: "location.name"
      date_posted: "listedAt"
      url: "applicationMethod.standardizedUrl"
      description: "description"
      salary: "salaryInsights.medianSalary"
    requires_auth: true
    auth_note: "Requires LinkedIn API credentials (Client ID, Client Secret, Access Token)"


  # =============================================================================
  # STATIC SCRAPING SOURCES (Public HTML pages)
  # =============================================================================

  - id: python_org
    name: Python.org
    type: static
    search_url: "https://www.python.org/jobs/?q={keyword}"
    selectors:
      job_selector: "ol.list-recent-jobs > li"
      title: "span.listing-company-name a"
      company: "span.listing-company-name"
      location: "span.listing-location a"
      date_posted: "span.listing-posted time"
      url: "span.listing-company-name a"

  # =============================================================================
  # SELENIUM-BASED SOURCES (Dynamic content, JavaScript-heavy)
  # =============================================================================


  - id: ziprecruiter
    name: ZipRecruiter
    type: dynamic
    search_url: "https://www.ziprecruiter.com/candidate/search?search={keyword}&location=Remote"
    selectors:
      job_selector: ".job_result"
      title: ".job_title"
      company: ".company_name"
      location: ".location"
      date_posted: ".job_age"
      url: ".job_title a"
    scroll_count: 3
    requires_auth: false