version: "3.8"

services:
  server:
    build:
      context: ../../server
      dockerfile: Dockerfile
    container_name: talenttrek-server-container
    volumes:
      - ../../server:/app
      - ../../server/data_output:/app/data_output
      - ../../server/config:/app/src/config
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - ../../server/.env
    environment:
      - PYTHONPATH=/app

  app:
    build:
      context: ../../app
      dockerfile: Dockerfile
    container_name: talenttrek-app-container
    volumes:
      - ../../app:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=production
